**Numpy**

Veri bilimi için olmazsa olmaz kütüphanelerdendir.
Açılımı numerical python.
Görüntü işleme vision kısmında daha çok kullanılır.
* Numpy -> numerical Python
* python nesnelerinin 50 katı kadar hızlı işlem yapmamızı sağlıyor
* hız noktasında artısı var, veriler belirli bir yerde saklandığı için
numpy arrayleri listelerden daha hızlı
* pip install numpy

In [1]:
import numpy as np 

Numpy ndarray nesnesi oluşturalım -> daha çok dizilerle çalışmak amacıyla kullanılıyor

In [2]:
nd = np.array([1,2,3,4,5,6,7])

print(nd)

[1 2 3 4 5 6 7]


In [3]:
print(type(nd))

<class 'numpy.ndarray'>


Dizilerde Boyutlar nd - n dimensional

In [4]:
# 0-Boyut
nd = np.array(35)

print(nd)

35


In [14]:
# 1-Boyut
nd = np.array([1,2,3])

print(nd)

[1 2 3]


In [16]:
# 2-Boyut
nd_2 = np.array([[1,2,3], [4,5,6]])

print(nd_2)

[[1 2 3]
 [4 5 6]]


In [17]:
# 3-Boyut
nd_3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [11,10,12]]])

print(nd_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 10 12]]]


In [18]:
# Dizinin boyutunu alma 

print(nd_3.ndim)
print(nd_2.ndim)

3
2


In [19]:
# Çok boyutlu diziler

nd = np.array([1,2,3], ndmin = 2)

print(nd)
print(nd.ndim)

[[1 2 3]]
2


In [20]:
# dizinin satır ve sütun bilgilerini alma -> shape

print(nd_3.shape)

(2, 2, 3)


In [21]:
# dizinin satırı ve sütun değerlerini değiştirme -> reshape
nd = np.array([1,2,3,4,5,6,7,8,9,0])

print(nd.shape)

(10,)


In [ ]:
print(nd.reshape[5,2])

In [23]:
# arange()

nd = np.arange(0, 10, 2)

print(nd)

[0 2 4 6 8]


In [25]:
# Dizi elemanlarına erişim
nd = np.array([1,2,3,4,5])

print(nd[2])

3


In [36]:
nd_2 = np.array([[1,2,3], [4,5,6]])

print(nd_2[1, 2])
print(nd_2[0, -1])

6
3


In [38]:
nd = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(nd)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [39]:
print(nd[0, 1, 2])

6


In [41]:
# numpy slicing işlemi

nd = np.array([1,2,3,4,5,6,7,8])
print(nd[:4])

[1 2 3 4]


In [45]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.random.random((2,3))

array([[0.53947881, 0.38972155, 0.82622664],
       [0.92113012, 0.33987154, 0.83258785]])

In [52]:
np.linspace(4, 5, num = 5) # 4 ile 5 aralığında 5 sayı ekle, aralıklar eşit

array([4.  , 4.25, 4.5 , 4.75, 5.  ])

In [54]:
np.linspace(4, 5, 5, endpoint = False) # 5 i almadı

array([4. , 4.2, 4.4, 4.6, 4.8])

In [56]:
np.full((2,3), 8) # doldurmak istediğin değeri giriyorsun

array([[8, 8, 8],
       [8, 8, 8]])

In [58]:
# matrisleri birleştirmek 
nd1 = np.array([1,2,3])
nd2 = np.array([4,5,6])

nd3 = np.concatenate([nd1, nd2])
print(nd3)

[1 2 3 4 5 6]


In [59]:
my_list = [1,2,3]
nd2 = np.array([4,5,6])

nd3 = np.concatenate([my_list, nd2])
print(nd3)

[1 2 3 4 5 6]
